name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.nodejs-version }}
      - name: Get dependencies cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run continous integration
        run: yarn ci
      - name: Build application
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://manuel-mueller.de --delete
